name: wv_user_agent
description: A simple Flutter plugin to get the user agent of the device using a native WebView.
version: 1.0.0
homepage: https://github.com/jakkimcfly/wv_user_agent
repository: https://github.com/jakkimcfly/wv_user_agent
documentation: https://github.com/jakkimcfly/wv_user_agent
issue_tracker: https://github.com/jakkimcfly/wv_user_agent/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jakkimcfly.wv_user_agent
        pluginClass: WvUserAgentPlugin
      ios:
        pluginClass: WvUserAgentPlugin